name: Glance Dashboard
version: "1.0.0"
slug: glance
description: Un dashboard self-hosted per Home Assistant.
arch:
  - amd64
  - armv7
  - arm64
startup: services
boot: auto
ingress: true
ingress_port: 8080
panel_icon: mdi:view-dashboard
panel_title: Glance
ports:
  8080/tcp: 8080
map:
  - config:rw
schema: {}
